@extends('layouts.dashboard')

@section('innerContent')
    <h1 class="titles">Team Builder</h1>
    <hr/>
    @include('site.teamBuilder.common.topMenu')
    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam viverra mi elit. Sed auctor, est a rhoncus convallis, metus mi vestibulum libero, ac iaculis risus orci accumsan dui. Nulla sit amet turpis ut erat vehicula vestibulum quis non enim. Donec lacinia et tortor ut aliquet. Mauris ante mi, convallis in libero quis, suscipit sollicitudin quam. Etiam fringilla consequat posuere. Ut sit amet odio sit amet odio dignissim suscipit eget id velit. Nunc tincidunt vestibulum justo, nec blandit elit. Cras et nisi hendrerit, gravida elit suscipit, molestie leo. Nulla eleifend porttitor porta. Etiam elementum purus at nunc tristique, in blandit ipsum pretium. Nam finibus, orci non mollis malesuada, lectus eros iaculis purus, varius ultrices est mauris at mi.</p>
        <p>Cras sagittis mattis nisl nec vehicula. Pellentesque faucibus finibus est, non vehicula orci consectetur sit amet. In dapibus fringilla mauris in euismod. Donec varius sem in ipsum convallis, eu blandit massa tincidunt. Quisque vitae nunc vitae dolor feugiat sollicitudin at sed justo. Nunc pulvinar eros et aliquam facilisis. Quisque mattis nisl tempor, tincidunt erat vitae, auctor risus. Pellentesque lacus tortor, tincidunt sed tortor eget, aliquet luctus lectus. Nam nibh sapien, faucibus nec mi ut, ultrices feugiat lacus. Suspendisse imperdiet, dui eu rhoncus ornare, metus magna semper purus, id aliquet est felis viverra nisl. Sed accumsan nec libero non rhoncus.</p>
        <p>Nunc tincidunt a mauris eu porta. Proin tristique porttitor metus vel facilisis. Mauris et elit nec nibh laoreet facilisis sed nec orci. Phasellus quis luctus magna, eget aliquet velit. Praesent velit purus, iaculis in scelerisque tempus, faucibus ac libero. Curabitur pharetra urna non metus pulvinar volutpat. Cras sit amet eros ac est volutpat posuere. Cras pulvinar metus sit amet risus elementum molestie. Praesent vel arcu rhoncus, ultrices dolor ac, posuere magna. Proin in odio quis velit posuere tincidunt a nec mauris. Etiam sodales consequat posuere. In at ullamcorper eros, id porta elit. Nunc in eros nibh.</p>
        <p>Vestibulum aliquet velit quis erat condimentum egestas. Ut euismod ultricies eleifend. Integer congue massa gravida consequat fermentum. Nullam convallis nisl ac sem commodo bibendum. Quisque mauris eros, sodales at faucibus et, rutrum sit amet sem. Vestibulum ac dapibus orci. Suspendisse varius, magna at tristique aliquam, eros risus posuere odio, vitae gravida orci ligula sit amet sapien. Mauris sollicitudin, lectus fermentum lobortis interdum, neque ipsum convallis quam, at tempus magna tortor quis orci. Quisque id porta lorem, vel placerat libero. Donec mauris mauris, sollicitudin id ligula at, consequat iaculis orci. Proin vel leo nisi. Duis ut lacus in metus suscipit fermentum at sed augue. Vivamus porttitor sit amet nibh convallis elementum. Praesent a lorem eu quam dignissim mattis vitae eu nisl. Donec id ligula consectetur, posuere sapien ut, dapibus nulla. Vivamus at lectus dui.</p>
    </div>
@endsection